apiVersion: v1
kind: Secret
metadata:
  name: camvote-secrets
type: Opaque
data:
  # Values must be base64 encoded strings. 
  # Example: "mysecretpassword" encoded is "bXlzZWNyZXRwYXNzd29yZA=="
  DATABASE_URL: bXlzZWNyZXRwYXNzd29yZA== 
  JWT_SECRET: c3VwZXJzZWNyZXRqd3R0b2tlbg==