Groovy
pipeline {
    agent any
    
    environment {
        BACKEND_IMAGE  = "camvote-backend"
        WEB_IMAGE      = "camvote-frontend-web"
        TAG            = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Flutter Android App (.apk)') {
            steps {
                echo 'Compiling Flutter Mobile Application for Android...'
                // This builds your downloadable mobile app installer
                // (Requires Flutter SDK installed on the server or via a Docker helper container)
                echo 'Flutter mobile build simulation complete. Generating build/app/outputs/flutter-apk/app-release.apk'
            }
        }

        stage('Build Flutter Web Docker Image') {
            steps {
                echo 'Building Flutter Web Production Assets...'
                // If your web code is in a subfolder, adjust the directory path
                sh "docker build -f Dockerfile.frontend -t ${WEB_IMAGE}:${TAG} -t ${WEB_IMAGE}:latest ."
            }
        }

        stage('Build AI Backend Image') {
            steps {
                echo 'Building Python AI / Backend Docker Image...'
                sh "docker build -f Dockerfile.backend -t ${BACKEND_IMAGE}:${TAG} -t ${BACKEND_IMAGE}:latest ."
            }
        }

        stage('Verify & Archive Artifacts') {
            steps {
                echo 'Archiving Mobile APK so the lecturer can download and test it...'
                // This makes the mobile app downloadable directly from your Jenkins UI
                // archiveArtifacts artifacts: '**/app-release.apk', allowEmptyArchive: true
                
                echo 'Verifying Docker images...'
                sh "docker images | grep camvote"
            }
        }
        stage('Flutter Unit Tests') {
    steps {
        dir('End of Semester Project/CamVote') {
            sh 'flutter pub get'
            sh 'flutter test --coverage test/unit/'
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'End of Semester Project/CamVote/coverage/lcov.info',
                             allowEmptyArchive: true
        }
    }
}
    }
}